### ISSUE TITLE
Cant download mods

### ISSUE THREAD

**Issue by CraigLee247** [PistolRcks/curseforge-mass-downloader#5]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\curseforge-mass-downloader-master\main.py", line 74, in <module>
    data = json.loads(rq.get(f"https://curse.nikky.moe/api/addon/{id}").content) # Put the request's data into a Python-readable format
  File "C:\Users\user\AppData\Roaming\Applications\VS22\Shared\Python39_64\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Roaming\Applications\VS22\Shared\Python39_64\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Roaming\Applications\VS22\Shared\Python39_64\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PistolRcks** [comment]
Unfixable due to a [dependency breaking](https://github.com/NikkyAI/CurseProxy/issues/9). Closing.
